name: NSTGRO Research Docker Image Publish CI

# trigger workflow when docker image build workflow is complete
on:
  workflow_run:
    workflows: [NSTGRO Research Docker Image Build CI]
    types:
      - completed

# workflow
jobs:
  # job proceeds differently depending on completion status of triggering workflow
  on-success:
    # unique identifier for job
    publish_docker_image:
      # name of job
      name: Publish Docker Image Job
      # type of machine to run job on
      runs-on: ubuntu-latest
      # check success of triggering workflow
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      steps:
        - name: Print triggering workflow success message
          run: echo "The build docker image workflow completed successfully!"
        - name: Print starting message
          env:
            DOCKER_IMAGE_NAME: NSTGRO Research Docker Image
          run: echo "Starting to publish $DOCKER_IMAGE_NAME to GitHub Container Registry"
        # TODO
  on-failure:
    # unique identifier for job
    cannot_publish_docker_image:
      # name of job
      name: Cannot Publish Docker Image Job
      # type of machine to run job on
      runs-on: ubuntu-latest
      # check success of triggering workflow
      if: ${{ github.event.workflow_run.conclusion == 'failure' }}
      steps:
        - name: Print triggering workflow failure message
          run: echo "The build docker image workflow failed :("
