name: NSTGRO Research Docker Image Build Check CI

# trigger workflow when docker image build workflow is complete
on:
  workflow_run:
    workflows: ["NSTGRO Research Docker Image Build CI"]
    types: [completed]
    branches: [main, feature/create-docker-image]
# NOTE: workflow_run event is only triggered when this workflow file exists on main/default branch

# workflow
jobs:
  # job proceeds differently depending on completion status of triggering workflow
  # unique identifier for job
  confirm_docker_image_on_build_success:
    # name of job
    name: Confirm Docker Image Job
    # type of machine to run job on
    runs-on: ubuntu-latest
    # check success of triggering workflow
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Print triggering workflow success message
        run: echo "The build docker image workflow completed successfully!"
      - name: Print starting message
        env:
          DOCKER_IMAGE_NAME: NSTGRO Research Docker Image
        run: echo "The $DOCKER_IMAGE_NAME successfully built! Another workflow can build/publish it to the GitHub Container Registry"
  # unique identifier for job
  cannot_confirm_docker_image_on_build_failure:
    # name of job
    name: Cannot Confirm Docker Image Job
    # type of machine to run job on
    runs-on: ubuntu-latest
    # check success of triggering workflow
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Print triggering workflow failure message
        run: echo "The build docker image workflow failed :("
